### ISSUE TITLE
Unstable solution

### ISSUE THREAD

**Issue by matthias-durivet** [thepycoder/aoc_2022#1]
Hey there, cool repo you have here.
I was having a look and noticed a particularly interesting line of code on day 16 line 279 🤣 
https://github.com/thepycoder/aoc_2022/blob/master/src/day16.py#L279

Joking aside, cool to see that you're also playing and crushing it, in second place 😉 
Didn't really know how to contact you, so here's a GitHub issue.

**Comment by thepycoder** [comment]
🙃




Thanks though :D
